### ISSUE TITLE
working on OSX El Capitan 10.11 ?

### ISSUE THREAD

**Issue by toftrem** [paixaop/zwack#6]
Hello 
is this simulator work on El capitan OSX?
Trtying but have issue with XPC module

Error: Cannot find module 'xpc-connection'
Require stack:

**Comment by jhofeditz** [comment]
I was able to get zwack running on OSX using this command to install xpc-connection:
`npm install git://github.com/taoyuan/node-xpc-connection.git`
I can run the simulator now, but I can't see it as a bluetooth sensor from other devices

**Comment by mjunkmyjunk** [comment]
Im trying it on big sur and can't see the sensor from other devices as well.
